name: Spellcheck

on:
  push:
    branches:
      - main  # Replace with the branch name you want to trigger the workflow on

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install -y aspell

      - name: Spellcheck text files
        run: |
          find . -name "*.txt" -type f -print0 | xargs -0 -n1 aspell --check