name: Spellcheck

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  spellcheck:
    name: runner / spellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Check out code.
      uses: actions/checkout@v2
    - name: Spell Checker Action
      uses: wow-actions/spell-checker@v1.0.3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        include: |
          **/*.md
          **/*.txt

